"""empty message

Revision ID: 0a30a1c252f5
Revises: 0867707526eb
Create Date: 2020-11-25 23:40:29.859903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a30a1c252f5'
down_revision = '0867707526eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('user', sa.String(length=150), nullable=False))
    op.drop_constraint('token_username_key', 'token', type_='unique')
    op.create_unique_constraint(None, 'token', ['user'])
    op.drop_column('token', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'token', type_='unique')
    op.create_unique_constraint('token_username_key', 'token', ['username'])
    op.drop_column('token', 'user')
    # ### end Alembic commands ###
